// src/components/common/MultiSelect.tsx
import React, { useState, useRef, useEffect } from 'react';
import { ChevronDownIcon, XMarkIcon } from '@heroicons/react/24/outline';

interface Option {
  id: number | string;
  name: string;
  description?: string;
  color?: string;
  icon?: string;
  category?: string;
}

interface MultiSelectProps {
  options: Option[];
  selectedIds: (number | string)[];
  onChange: (selectedIds: (number | string)[]) => void;
  placeholder?: string;
  label?: string;
  disabled?: boolean;
  maxHeight?: string;
  showCategories?: boolean;
  allowSelectAll?: boolean;
  searchable?: boolean;
}

const MultiSelect: React.FC<MultiSelectProps> = ({
  options,
  selectedIds,
  onChange,
  placeholder = "Select options...",
  label,
  disabled = false,
  maxHeight = "max-h-60",
  showCategories = false,
  allowSelectAll = false,
  searchable = true
}) => {
  const [isOpen, setIsOpen] = useState(false);
  const [searchTerm, setSearchTerm] = useState('');
  const dropdownRef = useRef<HTMLDivElement>(null);
  const searchInputRef = useRef<HTMLInputElement>(null);

  // Close dropdown when clicking outside
  useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      if (dropdownRef.current && !dropdownRef.current.contains(event.target as Node)) {
        setIsOpen(false);
      }
    };

    document.addEventListener('mousedown', handleClickOutside);
    return () => document.removeEventListener('mousedown', handleClickOutside);
  }, []);

  // Focus search input when dropdown opens
  useEffect(() => {
    if (isOpen && searchable && searchInputRef.current) {
      setTimeout(() => searchInputRef.current?.focus(), 0);
    }
  }, [isOpen, searchable]);

  // Filter options based on search term
  const filteredOptions = options.filter(option =>
    option.name.toLowerCase().includes(searchTerm.toLowerCase()) ||
    (option.description && option.description.toLowerCase().includes(searchTerm.toLowerCase()))
  );

  // Group options by category if showCategories is true
  const groupedOptions = showCategories
    ? filteredOptions.reduce((groups, option) => {
        const category = option.category || 'Other';
        if (!groups[category]) {
          groups[category] = [];
        }
        groups[category].push(option);
        return groups;
      }, {} as Record<string, Option[]>)
    : { '': filteredOptions };

  const selectedOptions = options.filter(option => selectedIds.includes(option.id));

  const handleOptionToggle = (optionId: number | string) => {
    const newSelectedIds = selectedIds.includes(optionId)
      ? selectedIds.filter(id => id !== optionId)
      : [...selectedIds, optionId];
    onChange(newSelectedIds);
  };

  const handleSelectAll = () => {
    const allIds = filteredOptions.map(option => option.id);
    onChange(allIds);
  };

  const handleDeselectAll = () => {
    onChange([]);
  };

  const removeOption = (optionId: number | string) => {
    onChange(selectedIds.filter(id => id !== optionId));
  };

  return (
    <div className="relative" ref={dropdownRef}>
      {label && (
        <label className="block text-xs sm:text-sm font-medium text-gray-700 mb-1">
          {label}
        </label>
      )}

      {/* Selected Options Display */}
      <div
        className={`
          min-h-[38px] sm:min-h-[42px] w-full px-2 py-1.5 sm:px-3 sm:py-2 border border-gray-300 rounded-md bg-white
          focus-within:ring-2 focus-within:ring-blue-500 focus-within:border-blue-500
          ${disabled ? 'bg-gray-50 text-gray-500 cursor-not-allowed' : 'cursor-pointer'}
        `}
        onClick={() => !disabled && setIsOpen(!isOpen)}
      >
        <div className="flex items-center justify-between">
          <div className="flex-1 flex flex-wrap gap-1">
            {selectedOptions.length === 0 ? (
              <span className="text-xs sm:text-sm text-gray-500">{placeholder}</span>
            ) : (
              selectedOptions.map(option => (
                <span
                  key={option.id}
                  className="inline-flex items-center px-1.5 py-0.5 sm:px-2 sm:py-1 rounded-md text-[10px] sm:text-xs font-medium bg-blue-100 text-blue-800"
                  style={option.color ? { backgroundColor: `${option.color}20`, color: option.color } : {}}
                >
                  {option.icon && <span className="mr-0.5 sm:mr-1 text-xs sm:text-sm">{option.icon}</span>}
                  <span className="truncate max-w-[80px] sm:max-w-none">{option.name}</span>
                  <button
                    type="button"
                    className="ml-0.5 sm:ml-1 hover:bg-blue-200 rounded-full p-0.5"
                    onClick={(e) => {
                      e.stopPropagation();
                      removeOption(option.id);
                    }}
                  >
                    <XMarkIcon className="h-2.5 w-2.5 sm:h-3 sm:w-3" />
                  </button>
                </span>
              ))
            )}
          </div>
          <ChevronDownIcon
            className={`h-4 w-4 sm:h-5 sm:w-5 text-gray-400 transition-transform flex-shrink-0 ml-1 ${isOpen ? 'rotate-180' : ''}`}
          />
        </div>
      </div>

      {/* Dropdown Menu */}
      {isOpen && (
        <div className={`absolute z-50 w-full mt-1 bg-white border border-gray-300 rounded-md shadow-lg ${maxHeight} overflow-hidden`}>
          {/* Search Input */}
          {searchable && (
            <div className="p-1.5 sm:p-2 border-b border-gray-200">
              <input
                ref={searchInputRef}
                type="text"
                placeholder="Search options..."
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
                className="w-full px-2 py-1.5 sm:px-3 sm:py-2 border border-gray-300 rounded-md text-xs sm:text-sm focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
              />
            </div>
          )}

          {/* Select All / Deselect All */}
          {allowSelectAll && (
            <div className="p-1.5 sm:p-2 border-b border-gray-200 flex gap-2">
              <button
                type="button"
                onClick={handleSelectAll}
                className="text-[10px] sm:text-xs text-blue-600 hover:text-blue-800"
              >
                Select All
              </button>
              <span className="text-gray-300">|</span>
              <button
                type="button"
                onClick={handleDeselectAll}
                className="text-[10px] sm:text-xs text-red-600 hover:text-red-800"
              >
                Deselect All
              </button>
            </div>
          )}

          {/* Options List */}
          <div className="overflow-y-auto max-h-48">
            {Object.keys(groupedOptions).length === 0 ? (
              <div className="p-2 sm:p-3 text-xs sm:text-sm text-gray-500 text-center">
                No options found
              </div>
            ) : (
              Object.entries(groupedOptions).map(([category, categoryOptions]) => (
                <div key={category}>
                  {/* Category Header */}
                  {showCategories && category && (
                    <div className="px-2 py-1.5 sm:px-3 sm:py-2 text-[10px] sm:text-xs font-semibold text-gray-500 bg-gray-50 border-b border-gray-200">
                      {category}
                    </div>
                  )}

                  {/* Options */}
                  {categoryOptions.map(option => {
                    const isSelected = selectedIds.includes(option.id);
                    return (
                      <div
                        key={option.id}
                        className={`
                          px-2 py-1.5 sm:px-3 sm:py-2 cursor-pointer hover:bg-gray-50
                          ${isSelected ? 'bg-blue-50' : ''}
                        `}
                        onClick={() => handleOptionToggle(option.id)}
                      >
                        <div className="flex items-center">
                          <input
                            type="checkbox"
                            checked={isSelected}
                            onChange={() => {}} // Handled by onClick
                            className="h-3.5 w-3.5 sm:h-4 sm:w-4 text-blue-600 focus:ring-blue-500 border-gray-300 rounded mr-2 sm:mr-3 flex-shrink-0"
                          />
                          <div className="flex-1 min-w-0">
                            <div className="flex items-center">
                              {option.icon && (
                                <span className="mr-1 sm:mr-2 text-sm sm:text-lg flex-shrink-0">{option.icon}</span>
                              )}
                              {option.color && (
                                <div
                                  className="w-2.5 h-2.5 sm:w-3 sm:h-3 rounded-full mr-1 sm:mr-2 flex-shrink-0"
                                  style={{ backgroundColor: option.color }}
                                />
                              )}
                              <span className="text-xs sm:text-sm font-medium text-gray-900 truncate">
                                {option.name}
                              </span>
                            </div>
                            {option.description && (
                              <div className="text-[10px] sm:text-xs text-gray-500 mt-0.5 sm:mt-1 truncate">
                                {option.description}
                              </div>
                            )}
                          </div>
                        </div>
                      </div>
                    );
                  })}
                </div>
              ))
            )}
          </div>

          {/* Selected Count */}
          {selectedIds.length > 0 && (
            <div className="px-2 py-1.5 sm:px-3 sm:py-2 bg-gray-50 border-t border-gray-200 text-[10px] sm:text-xs text-gray-600">
              {selectedIds.length} item{selectedIds.length !== 1 ? 's' : ''} selected
            </div>
          )}
        </div>
      )}
    </div>
  );
};

export default MultiSelect;

// src/components/common/MultiSelect.vue
<template>
  <div class="space-y-2">
    <!-- Search/Filter -->
    <div v-if="searchable" class="relative">
      <input
        v-model="searchQuery"
        type="text"
        :placeholder="searchPlaceholder"
        class="w-full px-3 py-2 pl-9 border border-gray-300 rounded-md focus:ring-2 focus:ring-primary-500 focus:border-primary-500"
      />
      <svg class="w-5 h-5 absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"/>
      </svg>
    </div>

    <!-- Selected count badge -->
    <div v-if="modelValue.length > 0" class="flex items-center gap-2 px-3 py-2 bg-primary-50 rounded-md">
      <svg class="w-5 h-5 text-primary-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"/>
      </svg>
      <span class="text-sm font-medium text-primary-700">
        {{ modelValue.length }} selected
      </span>
      <button
        v-if="modelValue.length > 0"
        type="button"
        @click="clearAll"
        class="ml-auto text-xs text-primary-600 hover:text-primary-700 font-medium"
      >
        Clear all
      </button>
    </div>

    <!-- Options list with checkboxes -->
    <div class="border border-gray-300 rounded-md divide-y divide-gray-200 max-h-64 overflow-y-auto">
      <div v-if="filteredOptions.length === 0" class="px-4 py-8 text-center text-sm text-gray-500">
        {{ searchQuery ? 'No results found' : 'No options available' }}
      </div>
      
      <label
        v-for="option in filteredOptions"
        :key="option.id"
        class="flex items-center gap-3 px-4 py-3 hover:bg-gray-50 cursor-pointer transition-colors"
        :class="{ 'bg-primary-50': isSelected(option.id) }"
      >
        <!-- Checkbox -->
        <input
          type="checkbox"
          :checked="isSelected(option.id)"
          @change="toggleOption(option.id)"
          class="w-5 h-5 text-primary-600 border-gray-300 rounded focus:ring-primary-500"
        />
        
        <!-- Icon (if provided) -->
        <span v-if="option.icon" class="text-xl">{{ option.icon }}</span>
        
        <!-- Option content -->
        <div class="flex-1 min-w-0">
          <div class="text-sm font-medium text-gray-900">
            {{ option[labelKey] }}
          </div>
          <div v-if="option[descriptionKey]" class="text-xs text-gray-500 truncate">
            {{ option[descriptionKey] }}
          </div>
        </div>

        <!-- Color indicator (if provided) -->
        <div
          v-if="option.color"
          class="w-4 h-4 rounded-full border border-gray-300"
          :style="{ backgroundColor: option.color }"
        ></div>
      </label>
    </div>
  </div>
</template>

<script setup>
import { ref, computed } from 'vue'

const props = defineProps({
  modelValue: {
    type: Array,
    default: () => []
  },
  options: {
    type: Array,
    required: true
  },
  labelKey: {
    type: String,
    default: 'name'
  },
  descriptionKey: {
    type: String,
    default: 'description'
  },
  valueKey: {
    type: String,
    default: 'id'
  },
  searchable: {
    type: Boolean,
    default: true
  },
  searchPlaceholder: {
    type: String,
    default: 'Search...'
  }
})

const emit = defineEmits(['update:modelValue'])

const searchQuery = ref('')

// Filter options based on search
const filteredOptions = computed(() => {
  if (!searchQuery.value) return props.options
  
  const query = searchQuery.value.toLowerCase()
  return props.options.filter(opt => {
    const label = opt[props.labelKey]?.toLowerCase() || ''
    const desc = opt[props.descriptionKey]?.toLowerCase() || ''
    return label.includes(query) || desc.includes(query)
  })
})

// Check if option is selected
const isSelected = (optionId) => {
  return props.modelValue.includes(optionId)
}

// Toggle option selection
const toggleOption = (optionId) => {
  const newValue = isSelected(optionId)
    ? props.modelValue.filter(id => id !== optionId)
    : [...props.modelValue, optionId]
  
  emit('update:modelValue', newValue)
}

// Clear all selections
const clearAll = () => {
  emit('update:modelValue', [])
}
</script>
